// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdQ8WJq8Kc_exLhyd9rhBliU81spyD9Xk',
    appId: '1:293055519090:web:27b55d63e53151f4a625eb',
    messagingSenderId: '293055519090',
    projectId: 'early-bird-7a020',
    authDomain: 'early-bird-7a020.firebaseapp.com',
    storageBucket: 'early-bird-7a020.firebasestorage.app',
    measurementId: 'G-JZ02RFP3XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22BGDqGGXXYa2Sd6lnEmULXRb94_zEAg',
    appId: '1:293055519090:android:b6637bc2e4a06f83a625eb',
    messagingSenderId: '293055519090',
    projectId: 'early-bird-7a020',
    storageBucket: 'early-bird-7a020.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhqGz-7hNAq1QxW4bFIztl6GbhxMNcR18',
    appId: '1:293055519090:ios:669004a1e5f932caa625eb',
    messagingSenderId: '293055519090',
    projectId: 'early-bird-7a020',
    storageBucket: 'early-bird-7a020.firebasestorage.app',
    iosBundleId: 'com.earlybird.earlyBird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhqGz-7hNAq1QxW4bFIztl6GbhxMNcR18',
    appId: '1:293055519090:ios:669004a1e5f932caa625eb',
    messagingSenderId: '293055519090',
    projectId: 'early-bird-7a020',
    storageBucket: 'early-bird-7a020.firebasestorage.app',
    iosBundleId: 'com.earlybird.earlyBird',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdQ8WJq8Kc_exLhyd9rhBliU81spyD9Xk',
    appId: '1:293055519090:web:8caea355d59f12b6a625eb',
    messagingSenderId: '293055519090',
    projectId: 'early-bird-7a020',
    authDomain: 'early-bird-7a020.firebaseapp.com',
    storageBucket: 'early-bird-7a020.firebasestorage.app',
    measurementId: 'G-W66E4KGG5R',
  );
}
